backend:
  name: git-gateway
  branch: main

# local_backend:
#   url: http://localhost:8082/api/v1

publish_mode: editorial_workflow

media_folder: "/packages/_images"
public_folder: "/packages/_images"

collections:
  - name: "it-sec"
    label: "ITSec"
    label_singular: "ITSec"
    folder: "_content/ITsec"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: Body
        name: body
        widget: markdown